// creation-fournisseur.tsx
"use client"

import { useState, useEffect } from "react"
import { useFournisseur } from "@/contexts/fournisseur/fournisseur-context"
import { useLocalisation } from "@/contexts/localisation/localisation-context"
import { Building, MapPin, Phone, User, FileText, Home, X, Navigation, Shield, Plus, Key } from "lucide-react"
import { toast } from "react-toastify"
import api from "@/api/api"

const COLOR = "#76bc21"
const COLOR_HOVER = "#5f9a1a"

interface CreationFournisseurProps {
  onSuccess?: () => void
  onCancel?: () => void
  localisations?: any[]
  isLoadingLocalisations?: boolean
}

interface NominatimResponse {
  display_name: string
  address: {
    suburb?: string
    neighbourhood?: string
    quarter?: string
    city?: string
    town?: string
    village?: string
    municipality?: string
    state?: string
    country?: string
    [key: string]: string | undefined
  }
}

export default function CreationFournisseur({
  onSuccess,
  onCancel,
  localisations = [],
  isLoadingLocalisations = false,
}: CreationFournisseurProps) {

  const [formData, setFormData] = useState({
    nom: "", prenom: "", adresse: "", identification_fiscale: "", cin: "", localisation_id: "", contact: ""
  })

  const [isDetectingLocation, setIsDetectingLocation] = useState(false)
  const [currentLocationName, setCurrentLocationName] = useState<string>("")
  const [permissionDenied, setPermissionDenied] = useState(false)
  const [isCreatingLocation, setIsCreatingLocation] = useState(false)
  const [showLocationInput, setShowLocationInput] = useState(false)
  const [newLocationName, setNewLocationName] = useState("")
  const [existingFiscaleIds, setExistingFiscaleIds] = useState<string[]>([])
  const [isFiscaleIdDuplicate, setIsFiscaleIdDuplicate] = useState(false)
  const [isCreateButtonDisabled, setIsCreateButtonDisabled] = useState(false)
  const [cinError, setCinError] = useState<string>("")
  const [userCollectorCode, setUserCollectorCode] = useState<string>("")
  const [autoGeneratedCode, setAutoGeneratedCode] = useState<string>("")
  const [isGeneratingCode, setIsGeneratingCode] = useState(false)

  const { createFournisseur, isLoading, error, clearError, fournisseurs } = useFournisseur()
  const { createLocalisation } = useLocalisation()

  // Récupérer le code collecteur de l'utilisateur connecté
  useEffect(() => {
    const fetchUserCollectorCode = async () => {
      try {
        const response = await api.get('/user')
        if (response.data.success) {
          const user = response.data.data
          setUserCollectorCode(user.code_collecteur || "")
        }
      } catch (error) {
        console.error("Erreur lors de la récupération des infos utilisateur:", error)
      }
    }
    fetchUserCollectorCode()
  }, [])

  useEffect(() => {
    const fiscaleIds = fournisseurs.map(f => f.identification_fiscale)
    setExistingFiscaleIds(fiscaleIds)
  }, [fournisseurs])

  // Générer automatiquement le code quand l'utilisateur commence à remplir le formulaire
  useEffect(() => {
    if (userCollectorCode && !formData.identification_fiscale) {
      generateAutoCode()
    }
  }, [userCollectorCode, formData.prenom])

  const generateAutoCode = async () => {
    if (!userCollectorCode || isGeneratingCode) return
    
    setIsGeneratingCode(true)
    try {
      // Récupérer tous les fournisseurs existants
      const response = await api.get('/fournisseurs')
      if (response.data.success) {
        const allFournisseurs = response.data.data
        
        // Filtrer les fournisseurs qui commencent par le code du collecteur
        const userFournisseurs = allFournisseurs.filter((f: any) => 
          f.identification_fiscale && f.identification_fiscale.startsWith(userCollectorCode)
        )
        
        const count = userFournisseurs.length + 1
        const sequenceNumber = String(count).padStart(3, '0')
        const generatedCode = `${userCollectorCode}-F${sequenceNumber}`
        
        // Vérifier si le code généré n'existe pas déjà (cas improbable)
        if (!existingFiscaleIds.includes(generatedCode)) {
          setAutoGeneratedCode(generatedCode)
          setFormData(prev => ({ ...prev, identification_fiscale: generatedCode }))
        } else {
          // Si le code existe déjà, essayer le suivant
          const nextSequenceNumber = String(count + 1).padStart(3, '0')
          const nextCode = `${userCollectorCode}-F${nextSequenceNumber}`
          setAutoGeneratedCode(nextCode)
          setFormData(prev => ({ ...prev, identification_fiscale: nextCode }))
        }
      }
    } catch (error) {
      console.error("Erreur lors de la génération du code:", error)
    } finally {
      setIsGeneratingCode(false)
    }
  }

  useEffect(() => {
    if (formData.identification_fiscale.trim()) {
      const isDuplicate = existingFiscaleIds.includes(formData.identification_fiscale.trim())
      setIsFiscaleIdDuplicate(isDuplicate)
      setIsCreateButtonDisabled(isDuplicate)
      
      if (isDuplicate) {
        toast.warning("Le code fournisseur existe déjà, veuillez le remplacer")
      }
    } else {
      setIsFiscaleIdDuplicate(false)
      setIsCreateButtonDisabled(false)
    }
  }, [formData.identification_fiscale, existingFiscaleIds])

  const validateCIN = (cin: string): boolean => {
    if (!cin || cin.trim() === "") {
      setCinError("")
      return true
    }
    
    if (cin.length !== 12) {
      setCinError("Le CIN doit contenir exactement 12 caractères")
      return false
    }
    
    setCinError("")
    return true
  }

  const extractSuburb = (data: NominatimResponse): string => {
    const suburb = data.address?.suburb || 
                   data.address?.neighbourhood || 
                   data.address?.quarter ||
                   data.address?.village ||
                   data.address?.town ||
                   data.address?.city;
    
    return suburb || "Quartier non spécifié";
  }

  const detectCurrentLocation = async () => {
    if (!navigator.geolocation) {
      toast.error("Géolocalisation non supportée")
      return
    }

    setIsDetectingLocation(true)
    setCurrentLocationName("")
    setPermissionDenied(false)
    setShowLocationInput(false)

    try {
      const position = await new Promise<GeolocationPosition>((resolve, reject) => {
        navigator.geolocation.getCurrentPosition(resolve, reject, {
          enableHighAccuracy: true,
          timeout: 10000,
          maximumAge: 300000
        })
      })

      const lat = position.coords.latitude
      const lon = position.coords.longitude

      const response = await fetch(
        `https://nominatim.openstreetmap.org/reverse?format=json&lat=${lat}&lon=${lon}&addressdetails=1&zoom=18`
      )

      if (!response.ok) throw new Error("Erreur lors de la récupération de l'adresse")

      const data: NominatimResponse = await response.json()

      if (data && data.address) {
        const suburb = extractSuburb(data)
        setCurrentLocationName(suburb)
        setNewLocationName(suburb)
        setShowLocationInput(true)
        toast.success("Quartier détecté !")
        setFormData(prev => ({ ...prev, adresse: suburb }))
      }
    } catch (error: any) {
      toast.error("Erreur de localisation")
      if (error.message.includes("Permission")) setPermissionDenied(true)
    } finally {
      setIsDetectingLocation(false)
    }
  }

  const useDetectedLocation = async () => {
    if (!currentLocationName) return
    setIsCreatingLocation(true)

    try {
      const existing = localisations.find(loc => loc.Nom.toLowerCase() === currentLocationName.toLowerCase())
      if (existing) {
        setFormData(prev => ({ ...prev, localisation_id: existing.id.toString() }))
        toast.success("Localisation sélectionnée")
      } else {
        const newLoc = await createLocalisation(currentLocationName)
        setFormData(prev => ({ ...prev, localisation_id: newLoc.id.toString() }))
        toast.success("Nouvelle localisation créée")
      }
      setShowLocationInput(false)
    } catch (err: any) {
      toast.error(err.message || "Erreur localisation")
    } finally {
      setIsCreatingLocation(false)
    }
  }

  const createLocationManually = async () => {
    if (!newLocationName.trim()) {
      toast.error("Nom de localisation requis")
      return
    }
    setIsCreatingLocation(true)
    try {
      const newLoc = await createLocalisation(newLocationName.trim())
      setFormData(prev => ({ ...prev, localisation_id: newLoc.id.toString() }))
      setShowLocationInput(false)
      setNewLocationName("")
      toast.success("Localisation créée")
    } catch (err: any) {
      toast.error(err.message || "Erreur création localisation")
    } finally {
      setIsCreatingLocation(false)
    }
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    clearError()

    if (!validateCIN(formData.cin)) {
      toast.error("CIN invalide: doit contenir exactement 12 caractères")
      return
    }

    if (!formData.identification_fiscale.trim()) {
      toast.error("Le code fournisseur est obligatoire")
      return
    }
    if (existingFiscaleIds.includes(formData.identification_fiscale.trim())) {
      toast.error("Ce code fournisseur existe déjà")
      return
    }

    if (!formData.prenom.trim()) {
      toast.error("Le prénom est obligatoire")
      return
    }
    if (!formData.localisation_id) {
      toast.error("Veuillez sélectionner ou créer une localisation")
      return
    }

    try {
      const payload: any = {
        ...formData,
        localisation_id: Number(formData.localisation_id),
      }
      if (!payload.cin || payload.cin.toString().trim() === "") {
        delete payload.cin
      }

      const result = await createFournisseur(payload)

      if (result.success) {
        toast.success(`Fournisseur ${formData.identification_fiscale} créé avec succès`)
        setFormData({ nom: "", prenom: "", adresse: "", identification_fiscale: "", cin: "", localisation_id: "", contact: "" })
        setCurrentLocationName("")
        setNewLocationName("")
        setShowLocationInput(false)
        setCinError("")
        onSuccess?.()
      } else {
        toast.error(result.message || "Erreur lors de la création")
      }
    } catch (err: any) {
      toast.error(err.message || "Impossible de créer le fournisseur")
    }
  }

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target
    setFormData(prev => ({ ...prev, [name]: value }))
    
    if (name === "cin") {
      validateCIN(value)
    }
  }

  const handleGenerateCode = () => {
    generateAutoCode()
  }

  return (
    <div className="p-4 sm:p-6 lg:p-8 space-y-6 sm:space-y-8 max-w-4xl mx-auto">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3 sm:gap-4">
          <div className="p-2.5 sm:p-3 rounded-full flex-shrink-0" style={{ backgroundColor: COLOR }}>
            <Building className="w-7 h-7 sm:w-8 sm:h-8 text-white" />
          </div>
          <div>
            <h2 className="text-xl sm:text-2xl lg:text-3xl font-bold text-gray-900 leading-tight">
              Nouveau Fournisseur
            </h2>
            <p className="text-xs sm:text-sm lg:text-base text-gray-600">Ajoutez un fournisseur</p>
          </div>
        </div>
        <button onClick={onCancel} className="p-2 hover:bg-gray-100 rounded-full transition">
          <X className="w-5 h-5 sm:w-6 sm:h-6 text-gray-500" />
        </button>
      </div>

      {error && (
        <div className="bg-red-50 border border-red-200 text-red-800 px-4 py-3 rounded-lg text-sm">
          {error}
        </div>
      )}

      <form onSubmit={handleSubmit} className="space-y-5 sm:space-y-6">
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 sm:gap-6">
          <div className="space-y-1.5">
            <label className="block text-sm font-semibold text-gray-700">Prénom *</label>
            <div className="relative">
              <User className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 sm:h-5 sm:w-5" style={{ color: COLOR }} />
              <input
                name="prenom"
                type="text"
                value={formData.prenom}
                onChange={handleChange}
                required
                className="pl-9 sm:pl-10 w-full px-3 sm:px-4 py-2.5 sm:py-3 text-sm sm:text-base border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-offset-2 transition-all"
                style={{ "--tw-ring-color": COLOR } as React.CSSProperties}
                placeholder="Prénom (obligatoire)"
              />
            </div>
          </div>

          <div className="space-y-1.5">
            <label className="block text-sm font-semibold text-gray-700">Nom <span className="text-gray-400 font-normal">(optionnel)</span></label>
            <div className="relative">
              <User className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 sm:h-5 sm:w-5" style={{ color: COLOR }} />
              <input
                name="nom"
                type="text"
                value={formData.nom}
                onChange={handleChange}
                className="pl-9 sm:pl-10 w-full px-3 sm:px-4 py-2.5 sm:py-3 text-sm sm:text-base border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-offset-2 transition-all"
                style={{ "--tw-ring-color": COLOR } as React.CSSProperties}
                placeholder="Nom de famille"
              />
            </div>
          </div>
        </div>

        <div className="space-y-1.5">
          <label className="block text-sm font-semibold text-gray-700">Adresse complète <span className="text-gray-400 font-normal">(optionnel)</span></label>
          <div className="relative">
            <Home className="absolute left-3 top-3 h-4 w-4 sm:h-5 sm:w-5" style={{ color: COLOR }} />
            <textarea
              name="adresse"
              value={formData.adresse}
              onChange={handleChange}
              rows={3}
              className="pl-9 sm:pl-10 w-full px-3 sm:px-4 py-2.5 sm:py-3 text-sm sm:text-base border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-offset-2 transition-all resize-none"
              style={{ "--tw-ring-color": COLOR } as React.CSSProperties}
              placeholder="Lot, quartier, commune..."
            />
          </div>
        </div>

        <div className="space-y-1.5">
          <div className="flex items-center justify-between">
            <label className="block text-sm font-semibold text-gray-700">Code fournisseur *</label>
            {userCollectorCode && (
              <button
                type="button"
                onClick={handleGenerateCode}
                disabled={isGeneratingCode}
                className="flex items-center gap-1 text-xs text-blue-600 hover:text-blue-800 transition-colors"
              >
                <Key className="w-3 h-3" />
                {isGeneratingCode ? "Génération..." : "Générer automatiquement"}
              </button>
            )}
          </div>
          <div className="relative">
            <FileText className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 sm:h-5 sm:w-5" style={{ color: COLOR }} />
            <input
              name="identification_fiscale"
              type="text"
              value={formData.identification_fiscale}
              onChange={handleChange}
              readOnly
              required
              className={`pl-9 sm:pl-10 w-full px-3 sm:px-4 py-2.5 sm:py-3 text-sm sm:text-base border rounded-lg focus:outline-none focus:ring-2 focus:ring-offset-2 transition-all ${
                isFiscaleIdDuplicate ? 'border-red-500 focus:ring-red-500' : 'border-gray-300'
              }`}
              placeholder={isGeneratingCode ? "Génération du code..." : userCollectorCode ? `Code généré: ${userCollectorCode}-F001` : "Ex: 123456789"}
            />
          </div>
          {userCollectorCode && formData.identification_fiscale && !isFiscaleIdDuplicate && (
            <p className="text-xs text-green-600 mt-1 flex items-center gap-1">
              <Key className="w-3 h-3" />
              Code généré automatiquement basé sur votre code collecteur
            </p>
          )}
          {isFiscaleIdDuplicate && (
            <p className="text-red-600 text-sm mt-1 flex items-center gap-1">
              <Shield className="w-4 h-4" />
              Ce code existe déjà
            </p>
          )}
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 sm:gap-6">
          <div className="space-y-1.5">
            <label className="block text-sm font-semibold text-gray-700">CIN <span className="text-gray-400 font-normal">(optionnel)</span></label>
            <div className="relative">
              <FileText className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 sm:h-5 sm:w-5" style={{ color: COLOR }} />
              <input
                name="cin"
                type="text"
                value={formData.cin}
                onChange={handleChange}
                className={`pl-9 sm:pl-10 w-full px-3 sm:px-4 py-2.5 sm:py-3 text-sm sm:text-base border rounded-lg focus:outline-none focus:ring-2 focus:ring-offset-2 transition-all ${
                  cinError ? 'border-red-500 focus:ring-red-500' : 'border-gray-300'
                }`}
                style={{ "--tw-ring-color": COLOR } as React.CSSProperties}
                placeholder="Ex: 123456789012"
              />
            </div>
            {cinError && (
              <p className="text-red-600 text-sm mt-1 flex items-center gap-1">
                <Shield className="w-4 h-4" />
                {cinError}
              </p>
            )}
          </div>

          <div className="space-y-1.5">
            <label className="block text-sm font-semibold text-gray-700">Contact <span className="text-gray-400 font-normal">(optionnel)</span></label>
            <div className="relative">
              <Phone className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 sm:h-5 sm:w-5" style={{ color: COLOR }} />
              <input
                name="contact"
                type="text"
                value={formData.contact}
                onChange={handleChange}
                className="pl-9 sm:pl-10 w-full px-3 sm:px-4 py-2.5 sm:py-3 text-sm sm:text-base border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-offset-2 transition-all"
                style={{ "--tw-ring-color": COLOR } as React.CSSProperties}
                placeholder="Téléphone ou email"
              />
            </div>
          </div>
        </div>

        <div className="space-y-3">
          <label className="block text-sm font-semibold text-gray-700">Localisation *</label>
          
          <div className="flex flex-col sm:flex-row gap-3">
            <div className="relative flex-1">
              <MapPin className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 sm:h-5 sm:w-5" style={{ color: COLOR }} />
              <select
                name="localisation_id"
                value={formData.localisation_id}
                onChange={handleChange}
                required
                disabled={isLoadingLocalisations}
                className="pl-9 sm:pl-10 w-full px-3 sm:px-4 py-2.5 sm:py-3 text-sm sm:text-base border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-offset-2 transition-all appearance-none bg-white"
                style={{ "--tw-ring-color": COLOR } as React.CSSProperties}
              >
                <option value="">Choisir une localisation</option>
                {localisations.map((loc) => (
                  <option key={loc.id} value={loc.id}>{loc.Nom}</option>
                ))}
              </select>
            </div>

            <button
              type="button"
              onClick={detectCurrentLocation}
              disabled={isDetectingLocation || isLoading}
              className="px-4 py-2.5 border border-gray-300 rounded-lg hover:bg-gray-50 transition-all flex items-center justify-center gap-2 text-sm font-medium disabled:opacity-50"
            >
              <Navigation className={`h-4 w-4 ${isDetectingLocation ? 'animate-spin' : ''}`} />
              {isDetectingLocation ? 'Détection...' : 'Détecter'}
            </button>
          </div>

          {permissionDenied && (
            <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-3 text-sm text-yellow-800">
              Permission refusée. Activez la localisation dans votre navigateur.
            </div>
          )}

          {showLocationInput && currentLocationName && (
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 space-y-3">
              <p className="text-sm font-medium text-blue-900">
                Quartier détecté : <strong>{currentLocationName}</strong>
              </p>
              <div className="flex flex-col sm:flex-row gap-2">
                <input
                  type="text"
                  value={newLocationName}
                  onChange={(e) => setNewLocationName(e.target.value)}
                  placeholder="Modifier si besoin"
                  className="flex-1 px-3 py-2 text-sm border border-blue-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
                <button
                  type="button"
                  onClick={useDetectedLocation}
                  disabled={isCreatingLocation}
                  style={{ backgroundColor: COLOR }}
                  className="px-4 py-2 text-sm font-medium text-white rounded-lg transition-all disabled:opacity-50"
                >
                  {isCreatingLocation ? 'Création...' : 'Utiliser'}
                </button>
              </div>
            </div>
          )}
        </div>

        <div className="flex flex-col-reverse sm:flex-row gap-3 pt-4 border-t">
          <button
            type="button"
            onClick={onCancel}
            disabled={isLoading}
            className="flex-1 px-6 py-3 border border-gray-300 rounded-lg text-gray-700 font-medium hover:bg-gray-50 transition-all disabled:opacity-50"
          >
            Annuler
          </button>
          <button
            type="submit"
            disabled={isLoading || isCreateButtonDisabled || isFiscaleIdDuplicate || !!cinError}
            style={{ backgroundColor: COLOR }}
            className="flex-1 px-6 py-3 rounded-lg text-white font-medium transition-all disabled:opacity-50 hover:opacity-90"
          >
            {isLoading ? "Création..." : "Créer le fournisseur"}
          </button>
        </div>
      </form>
    </div>
  )
}